# Generated by Django 5.1.6 on 2025-03-01 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVeriety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('CL', 'COLDICE'), ('GR', 'GRINGER'), ('PL', 'PLAIN'), ('EL', 'ELAICHI'), ('KI', 'KIWI')], max_length=2)),
            ],
        ),
    ]
