# Generated by Django 5.1.6 on 2025-03-01 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('CL', 'COLDICE'), ('GR', 'GINNGER'), ('PL', 'PLAIN'), ('EL', 'ELAICHI'), ('KI', 'KIWI')], max_length=2)),
                ('chai_description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='ChaiVeriety',
        ),
    ]
