# Generated by Django 5.1.6 on 2025-03-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_delete_chaiveriety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaivariety',
            options={'verbose_name_plural': 'Chai Varieties'},
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='chai_type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('CL', 'COLDICE'), ('GR', 'GINGER'), ('PL', 'PLAIN'), ('EL', 'ELAICHI'), ('KI', 'KIWI')], max_length=2),
        ),
    ]
